# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LifeToDo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LifeToDo
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'LifeToDoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LifeToDoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
